spring:
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/appinfo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#Mybatis配置别名
mybatis:
  type-aliases-package: com.lshsd.appinfo.pojo
  mapper-locations: classpath*:com/lshsd/appinfo/mapper/**/*.xml